site_name: Портфолио Синельников Никиты
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Главная: index.md
  - Лабораторные работы:
      - Обзор работ: labs/index.md
      - 2 семестр:
          - Лабораторная работа №1: labs/sem2/lab1.md
          - Лабораторная работа №2: labs/sem2/lab2.md
          - Лабораторная работа №3: labs/sem2/lab3.md
          - Лабораторная работа №4: labs/sem2/lab4.md
          - Лабораторная работа №5: labs/sem2/lab5.md
          - Лабораторная работа №6: labs/sem2/lab6.md
          - Лабораторная работа №7: labs/sem2/lab7.md
          - Лабораторная работа №8: labs/sem2/lab8.md
  - Об авторе: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

copyright: |
  &copy; 2026 <a href="https://github.com/jUmb0_juiceee" target="_blank">Синельников Никита</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jUmb0-juiceee
      name: jUmb0_juiceee на GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/bulka_s_maslomm
      name: Telegram
    - icon: fontawesome/solid/envelope
      link: mailto:niksinelnikov07@mail.ru
      name: Почта